### ISSUE TITLE
Add `get_version_string` from Sydent and Synapse

### ISSUE THREAD

**Issue by DMRobertson** [matrix-org/matrix-python-common#21] opened 2022-02-10 18:36 UTC
sydent/util/versionstring is a copy of synapse.util.versionstring. Neither of these are specific to identity servers or homeservers.

**Comment by clokep** [comment] 2022-02-10 19:16
Duplicate of #6!

**Closed as completed by clokep** 2022-02-10 19:16 UTC

**Comment by DMRobertson** [comment] 2022-02-10 23:33
Arg, and #6 is authored by me AND I even search for it!! Thanks.
